#!/bin/bash
###################################
#                                 #
# CA Automatic Turbo Mode         #
# Copyright 2022, Andrew Zawadzki #
#                                 #
###################################

if [[ -e /tmp/ca.turbo/PID ]]
 then
  logger "Stopping CA Turbo Mode"
  PID=`cat /tmp/ca.turbo/PID`
  logger "Terminating $PID"
  kill $PID
  rm /tmp/ca.turbo/PID
fi

