#!/bin/bash
###########################################################
#                                                         #
# CA Auto Turbo Mode copyright 2017-2023, Andrew Zawadzki #
#                                                         #
###########################################################

if [[ -e /tmp/ca.turbo/PID ]]
 then
  logger "Stopping CA Turbo Mode"
  PID=`cat /tmp/ca.turbo/PID`
  logger "Terminating $PID"
  kill $PID
  rm /tmp/ca.turbo/PID
fi

